<?php

namespace MarsupilamiBundle\Repository;

/**
 * MarsupilamiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarsupilamiRepository extends \Doctrine\ORM\EntityRepository
{
}
